# Generated by Django 2.0.3 on 2018-03-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('completada', models.BooleanField()),
            ],
        ),
    ]
